# An example configuration file for an optimisation

stages:
  Stage0: # Initialisation stage (see next stage for comments)
    scheme: 'init'
    nits: 200 # number of iterations for this stage
    lr: 0.05 # Adam optimiser learning rate

  Stage1: # chosen name of stage
      scheme: 'default' # one of 'init', 'default', 'shape', 'pose', 'deform'. See README for explanation
      nits: 500 # number of iterations for this stage
      lr: 0.03 # Adam optimiser learning rate

      loss_weights: # optional, any not provided will revert to default
          w_chamfer: 1.
          w_edge: 0.8
          w_normal: 0.02
          w_laplacian: 0.01

      custom_lrs: # optional, used to provide different learning rates to certain parameters
        joint_rot: 0.005

  Stage2:
    scheme: 'default'
    nits: 2000
    lr: 0.015

# Custom arguments. These will *overwrite* any command line arguments passed into the script
args:
  results_dir: fit3d_results
  shape_family_id: -1